docker:
  # image: g4s8/rultor:alpine3.10
  image: g4s8/rultor-jdk11:alpine3.10
architect:
  - amihaiemil
env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"
deploy:
  script: |-
    echo "JAVA HOME -----"
    echo ${JAVA_HOME}
    echo "---------------"
    mvn clean install -PgenDocs
merge:
  script: |-
    mvn clean install -Pcheckstyle
decrypt:
  settings.xml: "repo/rcfg/settings.xml.asc"
  pubring.gpg: "repo/rcfg/pubring.gpg.asc"
  secring.gpg: "repo/rcfg/secring.gpg.asc"
release:
  script: |-
    chmod +x ./rrv.sh
    ./rrv.sh
